<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbf62387639c603f3ce04d7e52d2cdf25
{
    public static $prefixLengthsPsr4 = array (
        'Q' => 
        array (
            'QuickBooksOnline\\API\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'QuickBooksOnline\\API\\' => 
        array (
            0 => __DIR__ . '/..' . '/quickbooks/v3-php-sdk/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbf62387639c603f3ce04d7e52d2cdf25::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbf62387639c603f3ce04d7e52d2cdf25::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
